package moraqui.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import moraqui.dao.GerenciarMoradiaDAO;
import moraqui.entity.GerenciarMoradia;

/**
 *
 * @author Thayna
 */
public class GerenciarMoradiaUI extends javax.swing.JFrame {
    String id;
    
    GerenciarMoradiaDAO ger;
    GerenciarMoradia moradia;
    
    public GerenciarMoradiaUI(String id) {
        initComponents();
        ger = new GerenciarMoradiaDAO();
        moradia = new GerenciarMoradia();
        this.id = id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMoradia = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuantMorador = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox();
        cbGenero = new javax.swing.JComboBox();
        btnIncluir = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        btnAlterar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_End = new javax.swing.JTextField();
        txt_min = new javax.swing.JTextField();
        txt_max = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_Pesq = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMoradia = new javax.swing.JTable();
        cbGenero2 = new javax.swing.JComboBox();
        ck_Valor = new javax.swing.JCheckBox();
        ck_End = new javax.swing.JCheckBox();
        ck_Tipo = new javax.swing.JCheckBox();
        ck_Gen = new javax.swing.JCheckBox();
        cbTipo2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("<html>Endereço <font color=\"red\">*</font>");

        jLabel2.setText("<html>CEP <font color=\"red\">*</font>");

        jLabel3.setText("<html>Tipo <font color=\"red\">*</font>");

        jLabel4.setText("<html>Área <font color=\"red\">*</font>");

        jLabel5.setText("<html>Gênero <font color=\"red\">*</font>");

        jLabel6.setText("Quantidade de Morador");

        jLabel7.setText("<html>Valor <font color=\"red\">*</font>");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apartamento", "Casa", "Edícula", "Kitnet", "Pensionato", "República" }));

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino", "Misto" }));

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel13.setText("<html>");

        jLabel14.setText("<html><font color=\"red\">* Campo Obrigatório</font>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnIncluir)
                            .addGap(30, 30, 30)
                            .addComponent(btnAlterar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco)
                            .addComponent(txtCep)
                            .addComponent(txtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtQuantMorador)
                            .addComponent(txtValor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnExcluir)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtQuantMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnCancelar))
                .addGap(40, 40, 40))
        );

        tabMoradia.addTab("Informações Moradia", jPanel1);

        txt_End.setEnabled(false);

        txt_min.setEnabled(false);
        txt_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_minActionPerformed(evt);
            }
        });

        txt_max.setEnabled(false);

        jLabel12.setText("Até:");

        btn_Pesq.setText("Pesquisar");
        btn_Pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqActionPerformed(evt);
            }
        });

        tableMoradia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMoradia.setEnabled(false);
        tableMoradia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMoradiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMoradia);

        cbGenero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino", "Misto" }));
        cbGenero2.setEnabled(false);

        ck_Valor.setText("Valor de");
        ck_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_ValorActionPerformed(evt);
            }
        });

        ck_End.setText("Endereço");
        ck_End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_EndActionPerformed(evt);
            }
        });

        ck_Tipo.setText("Tipo");
        ck_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_TipoActionPerformed(evt);
            }
        });

        ck_Gen.setText("Gênero");
        ck_Gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_GenActionPerformed(evt);
            }
        });

        cbTipo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apartamento", "Casa", "Edícula", "Kitnet", "Pensionato", "República" }));
        cbTipo2.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck_Valor)
                            .addComponent(ck_End)
                            .addComponent(ck_Tipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_min, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(cbTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_max, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(btn_Pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(ck_Gen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbGenero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addComponent(txt_End, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck_End))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGenero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck_Tipo)
                    .addComponent(ck_Gen)
                    .addComponent(cbTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btn_Pesq)
                    .addComponent(ck_Valor))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabMoradia.addTab("Consultar Moradia", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMoradia, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMoradia)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

        moradia.setMoradia(id, txtEndereco.getText(), txtCep.getText(), cbTipo.getSelectedItem().toString(),
            txtArea.getText(), cbGenero.getSelectedItem().toString(), txtQuantMorador.getText(), txtValor.getText());
        ger.cadastrar(moradia);

        //CAMPO OBRIGATÓRIO
        if(txtEndereco.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Endereço - Campo Obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        if(txtCep.getText().equals("")){
            JOptionPane.showMessageDialog(null, "CEP - Campo Obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        if(txtArea.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Área - Campo Obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        if(txtValor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Valor - Campo Obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        limpar();

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if(JOptionPane.showConfirmDialog(null,"Deseja realmente excluir esta moradia?","Excluir Moradia", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION)
            ger.excluir(moradia);
        limpar();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        moradia.setMoradia(id, txtEndereco.getText(), txtCep.getText(), cbTipo.getSelectedItem().toString(),
            txtArea.getText(), cbGenero.getSelectedItem().toString(), txtQuantMorador.getText(), txtValor.getText());       
        limpar();
        ger.alterar(moradia);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void limpar(){
        txtEndereco.setText("");
        txtCep.setText("");
        txtArea.setText("");
        txtQuantMorador.setText("");
        txtValor.setText("");
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txt_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_minActionPerformed

    }//GEN-LAST:event_txt_minActionPerformed

    private void btn_PesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqActionPerformed
        String condicoes = "CODLOCATOR = '"+id+"'";
        if(ck_End.isSelected())
                condicoes = " AND endereco LIKE '%"+txt_End.getText()+"%' ";
        if(ck_Tipo.isSelected())
                condicoes = condicoes + " AND tipo = "+cbTipo2.getSelectedItem().toString()+" ";
        if(ck_Gen.isSelected())
                condicoes = condicoes + " AND genero = "+cbGenero2.getSelectedItem().toString()+ " ";
        if(ck_Valor.isSelected()){
                if (txt_min.equals(""))
                    condicoes = condicoes + " AND valorunitario BETWEEN 0 AND "+txt_max.getText()+" ";
                else{
                    if (txt_max.equals(""))
                        condicoes = condicoes + " AND valorunitario BETWEEN "+txt_min.getText()+" AND 100000000";
                    else
                        condicoes = condicoes + " AND valorunitario BETWEEN "+txt_min.getText()+" AND "+txt_max.getText()+"";
                } 
        }
        DefaultTableModel model = ger.pesquisar(condicoes);
        tableMoradia.setModel(model);
    }//GEN-LAST:event_btn_PesqActionPerformed

    private void ck_EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_EndActionPerformed
        if (ck_End.isSelected())
            txt_End.setEnabled(true);
        else
            txt_End.setEditable(false);
    }//GEN-LAST:event_ck_EndActionPerformed

    private void ck_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_TipoActionPerformed
       if (ck_Tipo.isSelected())
           cbTipo2.setEnabled(true);
       else
           cbTipo2.setEnabled(false);
    }//GEN-LAST:event_ck_TipoActionPerformed

    private void ck_GenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_GenActionPerformed
        if (ck_Gen.isSelected())
            cbGenero2.setEnabled(true);
        else
            cbGenero2.setEnabled(false);
    }//GEN-LAST:event_ck_GenActionPerformed

    private void ck_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_ValorActionPerformed
        if (ck_Valor.isSelected()){
            txt_min.setEnabled(true);
            txt_max.setEnabled(true);
        }
        else{
            txt_min.setEnabled(false);
            txt_max.setEnabled(false);
        }
            
    }//GEN-LAST:event_ck_ValorActionPerformed

    private void tableMoradiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMoradiaMouseClicked
       int linha = tableMoradia.rowAtPoint(evt.getPoint());
        if(evt.getClickCount() == 1){
            
            txtEndereco.setText(tableMoradia.getModel().getValueAt(linha, 0).toString());
            txtCep.setText(tableMoradia.getModel().getValueAt(linha, 1).toString());
            txtArea.setText(tableMoradia.getModel().getValueAt(linha, 3).toString());
            txtQuantMorador.setText(tableMoradia.getModel().getValueAt(linha, 5).toString());
            txtValor.setText(tableMoradia.getModel().getValueAt(linha, 6).toString());
            moradia.setTipo(tableMoradia.getModel().getValueAt(linha, 2).toString());
            switch (tableMoradia.getModel().getValueAt(linha, 2).toString()) {
                 case "Apartamento":
                    cbTipo.setSelectedIndex(0);
                    break;
                case "Casa":
                    cbTipo.setSelectedIndex(1);
                    break;
                case "Edícula":
                    cbTipo.setSelectedIndex(2);
                    break;
                case "Kitnet":
                    cbTipo.setSelectedIndex(3);
                    break;
                case "Pensionato":
                    cbTipo.setSelectedIndex(4);
                    break;
                case "República":
                    cbTipo.setSelectedIndex(5);
                    break;
            }
            moradia.setGenero(tableMoradia.getModel().getValueAt(linha, 4).toString());
            switch (tableMoradia.getModel().getValueAt(linha, 4).toString()) {
                case "Feminino":
                    cbGenero.setSelectedIndex(0);
                    break;
                case "Masculino":
                    cbGenero.setSelectedIndex(1);
                    break;
            }
            
            moradia.setMoradia(id, txtEndereco.getText(), txtCep.getText(), cbTipo.getSelectedItem().toString(), txtArea.getText(), cbGenero.getSelectedItem().toString(), txtQuantMorador.getText(), txtValor.getText());
            
            tabMoradia.setSelectedIndex(0);
        }
        
        String codmoradia = ger.codMoradia(tableMoradia.getModel().getValueAt(linha, 0).toString());
        moradia.setCodMoradia(codmoradia);
    }//GEN-LAST:event_tableMoradiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnIncluir;
    private javax.swing.JToggleButton btn_Pesq;
    private javax.swing.JComboBox cbGenero;
    private javax.swing.JComboBox cbGenero2;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JComboBox cbTipo2;
    private javax.swing.JCheckBox ck_End;
    private javax.swing.JCheckBox ck_Gen;
    private javax.swing.JCheckBox ck_Tipo;
    private javax.swing.JCheckBox ck_Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabMoradia;
    private javax.swing.JTable tableMoradia;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtQuantMorador;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txt_End;
    private javax.swing.JTextField txt_max;
    private javax.swing.JTextField txt_min;
    // End of variables declaration//GEN-END:variables

    private void and(boolean equals) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
