/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moraqui.ui;

import moraqui.entity.GerenciarUsuario;
import moraqui.ui.GerenciarUsuarioLocatorLocatarioUI;
import moraqui.ui.GerenciarUsuarioUI;
import moraqui.ui.GerenciarMoradiaUI;
import moraqui.ui.GerenciarContratoUI;
import moraqui.ui.MarcarVisitaUI;

/**
 *
 * @author Jessica Terada
 */
public class InicioUI extends javax.swing.JFrame {
    GerenciarUsuario usuario;
    
    /**
     * Creates new form InicioUI
     */
    public InicioUI() {
        initComponents();
        usuario = new GerenciarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSair = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        menuMoradia = new javax.swing.JMenu();
        menuContrato = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuVisita = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 120));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moraqui/ui/slide_01.png"))); // NOI18N

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        menuUsuario.setText("Gerenciar Usuario");
        menuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuarioMouseClicked(evt);
            }
        });
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuUsuarioKeyPressed(evt);
            }
        });
        jMenuBar1.add(menuUsuario);

        menuMoradia.setText("Gerenciar Moradia");
        menuMoradia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMoradiaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMoradia);

        menuContrato.setText("Gerenciar Contrato");

        jMenuItem1.setText("Pesquisar Contrato");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuContrato.add(jMenuItem1);

        jMenuItem2.setText("Criar Contrato");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuContrato.add(jMenuItem2);

        jMenuBar1.add(menuContrato);

        menuVisita.setText("Marcar Visita");
        jMenuBar1.add(menuVisita);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
    
}//GEN-LAST:event_menuUsuarioActionPerformed

private void menuUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuUsuarioKeyPressed

}//GEN-LAST:event_menuUsuarioKeyPressed

private void menuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuarioMouseClicked
    if(GerenciarUsuario.getTipo().equals("Gerenciador")){
        GerenciarUsuarioUI gerenciarUsuarioUI = new GerenciarUsuarioUI();
        gerenciarUsuarioUI.setVisible(true);
    }
    if(GerenciarUsuario.getTipo().equals("Locatario")|| GerenciarUsuario.getTipo().equals("Locador")){
        GerenciarUsuarioLocatorLocatarioUI gerenciarUsuario = new GerenciarUsuarioLocatorLocatarioUI();
        
        gerenciarUsuario.setVisible(true);
    }
}//GEN-LAST:event_menuUsuarioMouseClicked

    private void menuMoradiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMoradiaMouseClicked

        if(GerenciarUsuario.getTipo().equals("Locador") || GerenciarUsuario.getTipo().equals("Locator")){
            GerenciarMoradiaUI gerenciar = new GerenciarMoradiaUI(usuario.getIdTipo());
        
            gerenciar.setVisible(true);
        }
    }//GEN-LAST:event_menuMoradiaMouseClicked

    private void menuContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuContratoMouseClicked

    }//GEN-LAST:event_menuContratoMouseClicked

    private void menuVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVisitaMouseClicked
        if(GerenciarUsuario.getTipo().equals("Locatario")){
            MarcarVisitaUI visita = new MarcarVisitaUI(usuario.getIdTipo());
            visita.setVisible(true);
        }
    }//GEN-LAST:event_menuVisitaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            GerenciarContratoConsultarUI a = new GerenciarContratoConsultarUI();
            a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(GerenciarUsuario.getTipo().equals("Locador")){
            GerenciarContratoUI gerenciarContrato = new GerenciarContratoUI(usuario.getIdTipo());
        
            gerenciarContrato.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuContrato;
    private javax.swing.JMenu menuMoradia;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVisita;
    // End of variables declaration//GEN-END:variables
}
